name: pr

on: ["pull_request"]

jobs:
  test-and-build:
    uses: autopp/spexec/.github/workflows/test.yml@main
    if: "!startsWith(github.head_ref, 'release/') || github.event.pull_request.head.fork"
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  teardown:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    needs: test-and-build
    steps:
    - name: Auto Merge
      if: contains(github.event.pull_request.body, '[auto merge]') && !contains(github.event.pull_request.title, '[WIP]') && !contains(github.event.pull_request.title, '[DNM]') && !github.event.pull_request.head.fork
      run: |
        # Request to merge button API
        hub api -X PUT /repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.number }}/merge
    - name: Notify to Slack
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
