name: push-main

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Use Cache
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Get dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        go mod download
        go install github.com/onsi/ginkgo/ginkgo@latest
    - name: Run Test
      run: make test
    - name: Build
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: build --snapshot --rm-dist
    - name: Save Artifact
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: ${{ github.workspace }}/dist/*/spexec
    - name: Notify to Slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,took,workflow,job,ref,message
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
